### ISSUE TITLE
Increased SSL/TLS Support

### ISSUE THREAD

**Issue by zero77** [rapid7/metasploit-payloads#107]
Can you add the option for strong SSL/TLS support with certificate pinning for all payloads.

**Comment by mubix** [comment]
If I recall correctly, certificate pinning is when a browser stores a certificate for a site so if it shows up as something other than what it knows is right it blocks the traffic to stop MITM. If this is what you are asking for this already exists thanks to @OJ and you can see how to set it up with the advanced options here: http://www.darkoperator.com/blog/2015/6/14/tip-meterpreter-ssl-certificate-validation
