### ISSUE TITLE
Multiple LHOST and RHOSTS Support

### ISSUE THREAD

**Issue by zero77** [rapid7/metasploit-payloads#110]
Can you add the option to have multiple RHOST and LHOST options support for every payload, in case one of your metasploits server is unreachable for whatever reason.

**Comment by OJ** [comment]
Individual stagers won't support more than one `LHOST` option at this point. It doesn't make sense to have multiple `RHOST`.

You can add new transports on the fly once your session has been established: https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Transport-Control

You can create stageless payloads that have support for multiple transports: https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Stageless-Mode
