### ISSUE TITLE
Possible meterpreter registry unicode bug

### ISSUE THREAD

**Issue by DiabloHorn** [rapid7/metasploit-payloads#127]
Hi,

I did a quick write up on a possible meterpreter bug https://diablohorn.com/2016/09/27/meterpreter-registry-unicode-quirk-work-around/, I link the blog cause it contains detailed information and a minor root cause analysis. If it's a bug it's contained in the file "c/meterpreter/source/extensions/stdapi/server/sys/registry/registry.c" between the lines 456 - 473.

TL;DR

Looks like meterpreter writes data to registry using Windows 'W' functions even if the data is just ASCII. Did not submit PR since unicode scares me :(

**Comment by OJ** [comment]
Thanks for the report @DiabloHorn, I'll get on it.
