### ISSUE TITLE
broken: python transport adding

### ISSUE THREAD

**Issue by DiabloHorn** [rapid7/metasploit-payloads#130]
After playing with the meterpreter extension the following popped up:

meterpreter > python_execute "import meterpreter.transport;print meterpreter.transport.add('tcp://172.16.218.145:8000')"
[-] Content written to stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "meterpreter\transport.py", line 62, in add
  File "meterpreter\core.py", line 216, in invoke_meterpreter
struct.error: bad char in struct format

After talking to TheColonial on IRC, he pasted the following:

it looks like the bridge code is busted.
hold up just one sec
https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/python/Lib/meterpreter/core.py#L216 <~ this line

**Comment by OJ** [comment]
Thanks @DiabloHorn I'm on it!
