### ISSUE TITLE
Android meterpreter - wakelock toggle to help maintain connection and prevent sleep

### ISSUE THREAD

**Issue by maxchill** [rapid7/metasploit-payloads#158]
I think it would be helpful to interactively be able to grab a wakelock during an android meterpreter session to ensure reliable network connection to the device.  
Perhaps there can be an automatic grab wakelock option for the case the device when the device is connected to a power source.

**Comment by timwr** [comment]
I have played with this before, however it seemed that because we had no foreground activity or notification it made the OS kill the app rather than putting it to sleep.
It's quite easy to implement so I'll put it together and we can see if it makes a difference on any devices.

**Comment by maxchill** [comment]
I got to thinking about this more.... it seems to me like GCM integration in android meterpreter in combination with sending the HIGH priority flag into messages may allow the meterpreter to reconnect?
