### ISSUE TITLE
Errors of androidpayload

### ISSUE THREAD

**Issue by hacksoldier98** [rapid7/metasploit-payloads#168]
Hi, I wanted to ask why after you copy the files / androidpayload / app / src / com / metasploit / stage / in order to put them in an app. But from those mistakes on android studio payload.java:

Error: (124, 13) error: can not find symbol variable PayloadTrustManager
Error: (81, 27) error: can not find symbol variable ConfigParser
Error: (81, 69) error: can not find symbol variable ConfigParser
Error: (79, 21) error: can not find symbol variable ConfigParser
Error: (77, 22) error: can not find symbol variable ConfigParser
Error: (75, 23) error: can not find symbol variable ConfigParser
Error: (74, 16) error: can not find symbol variable ConfigParser
Error: (73, 22) error: can not find symbol variable ConfigParser
Error: (73, 64) error: can not find symbol variable ConfigParser
Error: (72, 16) error: can not find symbol variable ConfigParser
Error: (71, 64) error: can not find symbol variable ConfigParser
Error: (71, 23) error: can not find symbol variable ConfigParser
Error: (69, 25) error: can not find symbol variable ConfigParser

What can I do?

**Comment by timwr** [comment]
Hi @hacksoldier98 
ConfigParser and PayloadTrustManager have moved here:
https://github.com/rapid7/metasploit-payloads/tree/master/java/meterpreter/shared/src/main/java/com/metasploit/stage

Is there a reason you're not just using msfvenom -x?

**Comment by hacksoldier98** [comment]
because I want to learn how the whole program and manually deploy the source code.
