### ISSUE TITLE
whitespace in python meterpreter is weird

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-payloads#186]
It's odd to see python code written with hard-tabs. Guess tab assassin missed a target!

If this is a size issue, I guess we could replace spaces with tabs during the payload encoding phase. Would suggest we replace hard-tabs with 4 spaces per the PEPs.

**Comment by h00die** [comment]
PEP is 4 space, but being the rest of msf is 2 space would it be better to be consistent on the project?

**Comment by busterb** [comment]
Ruby is 2 space, which is why most of MSF is. Would prefer whatever is consistent for the language. When in Rome, program like the Romans.

autocmd FileType python setl sw=4 sts=4 expandtab
autocmd FileType c set tabstop=4|set shiftwidth=4|set noexpandtab
autocmd FileType ruby set tabstop=2|set shiftwidth=2|set expandtab

**Comment by zeroSteiner** [comment]
I'm going to close this out because it was addressed in commit 39277d10bc0e78a341b1724a53e9c98ea2e8c2a6 which changed the hard tabs to spaces.
