### ISSUE TITLE
python meterpreter reverse_tcp sleep command seems to hang from msfconsole

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-payloads#202]
If you run 'sleep' on a python meterpreter session over reverse_tcp, the command dispatcher claims that it has hung, whereas python meterpreter thinks everything is OK:

```
meterpreter > sleep 20
[*] Telling the target instance to sleep for 20 seconds ...
[-] Error running command sleep: Rex::TimeoutError Operation timed out.
```

```
$ [*] running method core_machine_id
[*] running method core_enumextcmd
[*] running method core_loadlib
[*] running method stdapi_sys_config_getuid
[*] running method stdapi_sys_config_sysinfo
[*] running method core_set_uuid
[*] running method stdapi_net_config_get_interfaces
[-] method stdapi_net_config_get_routes was requested but does not exist
[*] running method core_transport_sleep
```

in _core_transport_sleep, it seems that the self.send_packet that gets returned as a response doesn't get processed by msfconsole. This is different than other commands where the response comes as a return to the command dispatcher:

```
    def _core_transport_sleep(self, request, response):
        seconds = packet_get_tlv(request, TLV_TYPE_TRANS_COMM_TIMEOUT)['value']
        self.send_packet(tlv_pack_response(ERROR_SUCCESS, response))
        if seconds:
            self.transport.deactivate()
            time.sleep(seconds)
            if not self.transport.activate():
                self.transport_change()
        return None
```

Note that even if you remove the code under 'if seconds', msfconsole still does not see the responses, which makes this look like an issue with self.send_packet(tlv_pack_response(ERROR_SUCCESS, response)) itself.

I experimented with this instead:
```
    def transport_sleep(self, seconds):
        time.sleep(1)
        self.transport.deactivate()
        time.sleep(seconds - 1)
        if not self.transport.activate():
            self.transport_change()

    def _core_transport_sleep(self, request, response):
        seconds = packet_get_tlv(request, TLV_TYPE_TRANS_COMM_TIMEOUT)['value']
        if seconds >= 1:
            t = threading.Thread(target = self.transport_sleep, args = (seconds,))
            t.start()
        return ERROR_SUCCESS, response
```

and msfconsole sees the response, but then somehow msfconsole sends pymet a shutdown command right afterward, which has obvious problems (maybe this is a bug in msfconsole):
```
$ [*] running method core_machine_id
[*] running method core_enumextcmd
[*] running method core_loadlib
[*] running method stdapi_sys_config_getuid
[*] running method stdapi_sys_config_sysinfo
[*] running method core_set_uuid
[*] running method stdapi_net_config_get_interfaces
[-] method stdapi_net_config_get_routes was requested but does not exist
[*] running method core_transport_sleep
[*] running method core_shutdown
```

I've run into issues like that in mettle as well - seems that any time msfconsole gets confused, it sends a shutdown, which means we're getting an error swallowed somewhere on the console side.

**Comment by OJ** [comment]
Thanks @busterb for logging this. I had similar problems in Windows with TCP transports, and solved in a rather awful way. First, I bail out of the server loop after [setting the transport to the next one](https://github.com/rapid7/metasploit-payloads/blob/a43afa7139f5f160b1524dde6ec2a10b700cccfd/c/meterpreter/source/common/arch/win/i386/base_dispatch.c#L316), then when the transport is reset, I do a [nasty dance](https://github.com/rapid7/metasploit-payloads/blob/8d84a89c5a96ec1cb148957432c77d2b46d983ab/c/meterpreter/source/server/win/server_transport_tcp.c#L882) that runs the clean up of the socket on another thread. You probably knew this already given you tried something similar. It does work ok on Windows.

Not sure how we can make this function nicely across all platforms in a way that doesn't make either end think there's something wrong.

**Comment by busterb** [comment]
We may need to bite the bullet and implement some sort of 'I don't care if I get a response' functionality. Right now the semantics are 'go away, but give me a kiss before we part!', which is tricky to get right compared to just going away.

**Comment by OJ** [comment]
Sounds good to me.
