### ISSUE TITLE
Meterpreter live mic listening?

### ISSUE THREAD

**Issue by BigBrotherIsWatchingYa** [rapid7/metasploit-payloads#221]
Hey, is it possible to add a feature for listening the microphone of a phone or a computer in live, like with webcam_stream, but with the microphone? It would be awesome, because record_mic is cool, but not very practical

**Comment by timwr** [comment]
Sounds like you're looking for mic_start. It's only available on OSX at the moment but we can add it to more platforms asap :)

**Comment by BigBrotherIsWatchingYa** [comment]
Ah? Maybe, I don't know, I don't have any OSX ^^'. Maybe that's what I'm looking for yeah, I hope you'll add it to the others plateforms, can't wait for the update ! :3

**Comment by wwebb-r7** [comment]
I have something like this in the planning stages for Windows 7+, with a few other items in the priority queue ahead of it.  It wouldn't hurt my feelings if someone else decided to run with it.

**Comment by timwr** [comment]
I can do android

**Comment by wwebb-r7** [comment]
I think it's safe to say that this is on the TODO list for all platforms it makes sense on, so I'm going to go ahead and close this.  Feel free to reopen if there's some other angle to it you feel should be explored.

**Comment by m15h3l** [comment]
@timwr, you have manage to listening live to the mic ?

**Comment by timwr** [comment]
This is implemented on the native OSX meterpreter only, I think @dmohanty-r7 made a start on Android but it's not currently implemented.

**Comment by m15h3l** [comment]
Ok Thanks

**Comment by timwr** [comment]
You're welcome to implement it and send us a pull request :+1:
