### ISSUE TITLE
Request: tor as transport for meterpreter

### ISSUE THREAD

**Issue by 1nsecure** [rapid7/metasploit-payloads#225]
As title says, it will be, at least, interesting to have built-in tor support in meterpreter payload.

**Comment by wwebb-r7** [comment]
It would certainly be interesting; however, given the architecture of Meterpreter and framework, it would be an incredible amount of work to implement correctly, especially when considering that it likely wouldn't benefit most of our users.

I wouldn't wait for it with bated breath, but we'd certainly be happy to evaluate any community submitted PR's towards it.

**Comment by sempervictus** [comment]
This is pretty easy today - all you need is a public http proxy facing into TOR, and a your reverse handler bound to a TOR-only address accessible via that proxy. Tlv crypto helps here since TLS is stripped, though MITM in negotiation is a concern.

**Comment by wwebb-r7** [comment]
Closing and filing under probably-never-happening/alternatives-exist/discussion-died.  Feel free to submit a new issue in continuation of this one if you feel it's warranted.

**Comment by sempervictus** [comment]
I'll note here that we do want socks4 support in tcp transport, and maybe stagers (at least stateless).
Ping @OJ: SOCKS transport thoughts?
