### ISSUE TITLE
Windows meterpreter crash

### ISSUE THREAD

**Issue by ssyy201506** [rapid7/metasploit-payloads#247]
Windows meterpreter crashes when switching transport from WinHTTP to WinInet.
It seems that the following line contains an unnecessary semicolon.
https://github.com/rapid7/metasploit-payloads/blob/c30d7ee34912b9cd4d886c23bfb3941f3bbf88b7/c/meterpreter/source/common/packet_encryption.c#L458

**Comment by busterb** [comment]
yep, you're right! thanks for the catch - cc @bwatters-r7 for adding this to the payload tests

**Comment by OJ** [comment]
Sorry, that royal f#%k up is my fault :(
