### ISSUE TITLE
Migrate Crashes Meterpreter

### ISSUE THREAD

**Issue by zealias** [rapid7/metasploit-payloads#253]
Recent git clone version of metasploit-payloads. Migrate x86 -> x64, x86 -> x86, x64 -> x64 all crash meterpreter. Metasploit version(4.16.18-dev) is Kali(Linux Kali 4.9.0-kali4-686-pae #1 SMP Debian 4.9.30-2kali1 (2017-06-22) i686 GNU/Linux), not compiled.

Test system: Win7 x64

**Comment by busterb** [comment]
Http? Tcp?

**Comment by busterb** [comment]
OK, verified HTTP has an issue, but TCP looks fine.

**Comment by busterb** [comment]
Pushed a fix PR above, would you mind verifying the fix?

**Comment by busterb** [comment]
I'll go ahead and land this because I should have spotted it with the domain fronting PR. Thanks for the quick spot!

**Comment by zealias** [comment]
Great thanks! Using https, its not crashing now but getting this error message:
[-] Error running command migrate: NoMethodError undefined method `[]' for nil:NilClass

**Comment by busterb** [comment]
now you're going to have to give me a little more info - what exactly did you type, and was there anything in your framework.log file?

**Comment by zealias** [comment]
So after I receive a session, I use migrate [process id] as usual. Here's the stack trace from framework.log

[11/25/2017 22:21:08] [i(0)] core: windows/meterpreter/reverse_https: iteration 1: Successfully encoded with encoder x86/shikata_ga_nai (size is 180852)
[11/25/2017 22:21:53] [e(0)] meterpreter: Error running command migrate: NoMethodError undefined method `[]' for nil:NilClass
[11/25/2017 22:21:53] [d(0)] meterpreter: Call stack:
/usr/share/metasploit-framework/lib/rex/post/meterpreter/client_core.rb:749:in `generate_migrate_stub'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/client_core.rb:568:in `migrate'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1114:in `cmd_migrate'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_command'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:460:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `run_single'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:196:in `run'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:563:in `_interact'
/usr/share/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1380:in `cmd_sessions'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:460:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:454:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:206:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'

**Comment by busterb** [comment]
what transports are you using exactly? more than one?

**Comment by zealias** [comment]
reverse https. only one.

**Comment by busterb** [comment]
Suspecting a minor incompatibility with the latest metasploit-payloads and the previous version of metasploit-framework, since that backtrace indicates you're using a slightly mismatched pair. Is it possible for you to update framework to the latest git too?

**Comment by zealias** [comment]
yea sure. going to try that now.

**Comment by zealias** [comment]
which framework version are you using? i downloaded the nightly build 4.16.17+20171125113954~1rapid7-1 which is behind the Kali one.

**Comment by busterb** [comment]
just HEAD in CVS. The nightlies are up-to-date.

**Comment by zealias** [comment]
Confirmed working with git clone latest metasploit-framework (4.16.19-dev-65412cd2f1).

Thanks!
