### ISSUE TITLE
Android reverse_https payload doesn't connect to https handler

### ISSUE THREAD

**Issue by pudup** [rapid7/metasploit-payloads#267]
Reverse_https payloads only to connect to reverse_tcp handlers(and never manage to make a session obviously). Also they seem to be sending only tcp requests over the network instead of https requests.
Generated with latest meta framework. 
Android tcp payloads and windows https payloads work fine.

**Comment by timwr** [comment]
... surely it's working exactly as expected?
Use a reverse_tcp handler for a tcp payload. Use a reverse_https handler for a reverse_https payload.

**Comment by pudup** [comment]
I meant https payload makes no connection to a https handler on android at least.

**Comment by pudup** [comment]
It does however attempt to connect to a tcp handler and fails. Keeps sending a stage request but never finishes anything.

**Comment by timwr** [comment]
I can't reproduce this, android/meterpreter/reverse_https works fine for me. Join our IRC/slack and feel free to share the log of how you're generating the payload (and starting the handler).

**Comment by pudup** [comment]
Will do thanks
