### ISSUE TITLE
python meterpreter portfwd http service,download file problem

### ISSUE THREAD

**Issue by uyid** [rapid7/metasploit-payloads#282]
This code reads forward data. It gets stuck when downloading large files(eg 140M).
Suggest, jump out of the loop and return to the server when read enough data(eg 10k).

https://github.com/rapid7/metasploit-payloads/blob/39277d10bc0e78a341b1724a53e9c98ea2e8c2a6/python/meterpreter/meterpreter.py#L921-L930

**Comment by jmartin-r7** [comment]
This code was significantly refactored. Please validate if this is still an issue.
