### ISSUE TITLE
Fail-over LHOST for meterpreter payload 

### ISSUE THREAD

**Issue by illera88** [rapid7/metasploit-payloads#286]
Hi,

Is there a way to set multiple `LHOST` and `LPORT` in a meterpreter payload so an extra domain/ip is used in the case that the first one gets blocked or just for some reason doesn't resolve/connect?

Thank you

**Comment by busterb** [comment]
Meterpreter supports it internally, it is just not exposed in the UI.

**Comment by busterb** [comment]
LHOST as a parameter really makes this awkward though. We need to figure out how to expose the connection URLs instead.

**Comment by illera88** [comment]
How should I supply the multiple domains? Comma separated, semicolon?

Thanks @busterb

**Comment by OJ** [comment]
No, `LHOST` must only be a single domain.

If you want to support multiple domains to start with they have to be baked in as separate transports on startup. This isn't a trivial task though.

I'm working on something that's going to make this *much* easier. So watch this space.

**Comment by OJ** [comment]
FYI, initial support for adding transports in a much easier way via the Powershell extension should be coming soon, the PR is open here: https://github.com/rapid7/metasploit-payloads/pull/287

When landed, I'll throw some documentation together that will show you how to do this during startup.

**Comment by bwatters-r7** [comment]
There exists nothing that would allow that feature inside the payload, but you can change/add transports during the session.  Please see: https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Transport-Control

**Comment by OJ** [comment]
Now that #287 has landed, you've got the ability to do it with stageless payloads. Let us know how it goes!
