### ISSUE TITLE
Cross-compile c/meterpreter on GNU/Linux

### ISSUE THREAD

**Issue by plowsec** [rapid7/metasploit-payloads#303]
Hi there,
I was wondering if anyone succeeded in cross-compiling c/meterpreter on GNU/Linux ?
Since there is a docker for setting up the dev environnment, why not adding support for building the windows payloads ?

I tried to build the Visual Studio solution at /metasploit-payloads/c/meterpreter/workspace anyway with the msbuild that comes with mono but I couldn't fix the error I constantly get:
`error MSB4019: The imported project "/Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

Some help would be greatly appreciated !

**Comment by bcoles** [comment]
You may enjoy [mettle](https://github.com/rapid7/mettle).

`./make-all` will cross-compile mettle using bundled musl.

Also:

https://www.youtube.com/watch?v=zwUS4hqMYSY
https://www.youtube.com/watch?v=bk-MmvPOWMo

**Comment by timwr** [comment]
I have not tried on Linux but it would be cool if it worked.
On windows this works: https://buffered.io/posts/building-meterpreter-is-easy/
I do this in a windows VM (Ubuntu host) and use robocopy to copy the bins back to a shared folder.
I did not encounter that error.

**Comment by plowsec** [comment]
Yes indeed a VM may be a solution, but in my opinion the whole process would scale a lot better if cross-compilation was possible. I mean, a full featured VM is heavy compared to a ready to deploy docker container.

Of course, I would be happy to get my hands dirty if pointed in the right direction.

**Comment by plowsec** [comment]
Any news? It would be very convenient to be able to generate the meterpreter's DLLs with another compiler than Visual Studio, on another platform than Windows. Just think of the possibilities ;-)

**Comment by plowsec** [comment]
I have made Makefiles for metsrv, common, ReflectiveDLLInjection and backcompat (the latter is not completely done). You can find them in my fork of metasploit-payloads or https://github.com/plowsec/metasploit-payloads/blob/04229d1196a23207dc1f9d85304ac5bbeff1eaec/c/meterpreter/workspace/metsrv/CMakeLists.txt

For instance, to compile metsrv.x64.dll just do: `cmake workspace/metsrv && cd workspace/metsrv && make`

This is to show you it is possible to cross-compile meterpreter. However, I am not very good with Makefiles so it would be great if you guys helped.

Makefiles for Meterpreter are not only nice to have, it should be on the high priority list for the following reasons:
- Possible to automate the build process without a heavy Windows machine.
- Possible to ditch the Visual Studio compiler (C99 only...Jesus Christ).
- Possible to use CLANG and implement very nice and useful LLVM passes => obfuscator-llvm and additional passes WILL solve your antivirus problem. I know because if I have done it in a similar fashion (mass refactoring of meterpreter's source code with a libclang frontend) and I can show you the exact strings detected by Windows Defender (who said Machine Learning, again?).

We NEED this to obfuscate the code base and bypass AVs, so let's get it done right?

**Comment by plowsec** [comment]
That's great. I just made the first PR and let me know if I got anything wrong.

I will continue to work on it but I will require guidance (fixing the Makefile for backcompat is way over my head for instance) and tests (x86, x64, several Windows versions...).

Do we have some tests scripts to check that we didn't break any feature?

**Comment by realoriginal** [comment]
Fuck yes! make this happen. I might PR some shit to help, I'd LOVE for this

**Comment by kozlovsas** [comment]
If any testing needs to be done I would love to assist in any way I can!

**Comment by plowsec** [comment]
@kozlovsas Say no more: https://github.com/rapid7/metasploit-payloads/pull/341

Your help is greatly appreciated! :)

**Comment by arrowd** [comment]
Any progress on this?

**Comment by plowsec** [comment]
Sadly no, I don't have the time at the moment to pursue it, but I like I said I only wanted to initiate the whole thing, to show that it is possible. I think it's easy enough for anyone to contribute so I hope the community will do its wonders.

**Comment by smcintyre-r7** [comment]
This should be done now with the changes that were merged into v6. As far as I'm aware there are only two extensions which will not cross compile at this time (powershell and python). See PR #405 for more information.

I'm going to close this out as completed now.
