### ISSUE TITLE
Android meterpreter (record mic ) (wlan geolocate error)

### ISSUE THREAD

**Issue by MMLinuxer** [rapid7/metasploit-payloads#309]
so I've been getting these errors 
Tested on MiA1
Samsung S4

record mic can't actually record more than 20 second 
I thought It might be that the socket times out before the record has finished 
so I Set_timeouts to be 500 seconds nothing changed

[-] Error running command record_mic: Rex::TimeoutError Operation timed out.

another Error that I got when using Wlan_geolocate 

meterpreter > wlan_geolocate 
[-] Error running command wlan_geolocate: ArgumentError wrong number of arguments (given 3, expected 2)

I know this feature used to work before 
I believe this Error came up after updating metasploit 
I don't think this feature is that important 
I mean you can just get the victim's IP Address and query about it on some website
 
It would be great If you added gps based location as It's the most precise 
thank you .

**Comment by MMLinuxer** [comment]
great thank you 
will the problem of mic be fixed

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/issues/19154

Adding this as a feature request
