### ISSUE TITLE
Debug function dprintf did not work.

### ISSUE THREAD

**Issue by Green-m** [rapid7/metasploit-payloads#312]
Refer to this wiki: https://github.com/rapid7/metasploit-payloads/wiki/Debugging-Meterpreter(s)

I have set it in a file that I want to debug :
`#define DEBUGTRACE 1`

`dprintf("some debug string:xxx \n")`

And after rebuild and reload the extension, nothing captured by `Debugview`.

However, I use the native function `OutputDebugstringA` instead, it works well.

So I use something like this to debug:

```
void DebugOut(const char *fmt, ...)
{
  va_list args; 
  va_start(args, fmt); 
  char dbg_out[4096];
  vsprintf_s(dbg_out, fmt, args);
  va_end(args); 
  OutputDebugString(dbg_out);
}
```

Is the function `dprintf` problematic? 
ping @bwatters-r7

**Comment by timwr** [comment]
Are you sure you're including common.h? dprintf just ends up calling OutputDebugStringA anyway:
https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/common/common.h
You may need to put `#define DEBUGTRACE 1` before the includes.

**Comment by Green-m** [comment]
@timwr 
Nice, it works, need to add it to the head of the file.
I should inquiry you earlier, thanks a lot!
