### ISSUE TITLE
Compile Correctly with Visual Studio

### ISSUE THREAD

**Issue by anonymouz4** [rapid7/metasploit-payloads#326]
Does anybody now how to compile it correctly in Visual Studio?

For example I tried to compile `incognito2` for myself, after fixing a lot of errors, compiling works but it doesn't execute well.

When running `incognito.exe list_tokens -u` the execution in `list_tokens.c` exits/stops before reaching `printf("3")`, so there's a problem with the `ntReturn` line

```
NtQuerySystemInformation = (NTQUERYSYSTEMINFORMATION)GetProcAddress(GetModuleHandle("ntdll.dll"), "NtQuerySystemInformation");
NtQueryObject= (NTQUERYOBJECT)GetProcAddress(GetModuleHandle("ntdll.dll"), "NtQueryObject");
dwSize = 256*1000;
printf("1");
pProcessInfo = (PSYSTEM_PROCESS_INFORMATION)malloc(dwSize);
printf("2");
ntReturn = NtQuerySystemInformation(SystemProcessInformation, pProcessInfo, dwSize, &dwSize);
printf("3");
```
Any idea why? Do I manually have to link ntdll.lib or something? (only thing I did is add all headers and c files in a empty c++ visual studio project, fix some errors and run)

**Comment by FireFart** [comment]
https://github.com/rapid7/metasploit-payloads/tree/master/c/meterpreter#building---windows

**Comment by anonymouz4** [comment]
But it doesn't work. Just re cloned and done all steps and errors. Have you even ever successfully compiled it or just posted the link?

**Comment by OJ** [comment]
@anonymouz4 I'd highly recommend you adjust your attitude if you expect to get help in here.

My guess is you're using the wrong version of Visual Studio. Can you post some information on your current set up please.

**Comment by OJ** [comment]
Also, we're happy to help with the compilation of the source in this repo, but we're not going to provide general support for compiling other projects (such as incognito). You'll have to get in touch with the respective authors for help with those.

**Comment by anonymouz4** [comment]
@OJ It wasn't meant to be rude, i was just interested to see whether he compiled it or not.

I'm using Visual Studio 2017 on Win10 Pro.

Steps I did:
```
- git clone https://github.com/rapid7/metasploit-payloads
- cd metasploit-payloads
- git submodule init && git submodule update
- cd c\meterpreter
- make x64
- Error: Visual Studio Version not installed (only bc VS 2013 was apparently specified)
- Opened workspace/meterpreter.sln
- Selected 'Release' & 'x64'
- Selected all Projects, right-click properties and set SDK to 10.x and VS to my VS 2017
- ran 'make x64' again, still errors (object files not build)
```

**Comment by OJ** [comment]
![image](https://user-images.githubusercontent.com/28896/52450821-66196e00-2b88-11e9-8714-800ae6679a65.png)

**Comment by OJ** [comment]
There's work required it making it build correctly under VS 2017, including making sure that the correct platform toolset is installed. Right now, if you want to build it, please use VS 2013. We'll get it working under VS 2017 at some point soon when we know we can continue to support the appropriate platform toolset going back as far as XP. Thanks.

**Comment by anonymouz4** [comment]
I've read the article. I couldn't think of a good reason on why it shouldn't run on 2017, thats why

Is there no way to get it to run exept 2013

**Comment by anonymouz4** [comment]
@OJ  ok

**Comment by OJ** [comment]
I can think of a lot of good reasons, and that's why the instructions are as they are. Sorry, that's the current state of play. There's more to it than meets the eye.
