### ISSUE TITLE
Android Studio Meterpreter 

### ISSUE THREAD

**Issue by MircoCagni** [rapid7/metasploit-payloads#328]
I want compile my personal app with android Meterpreter inside, how can I add the payload inside my app? I use android studio.

Thanks

**Comment by timwr** [comment]
You can just include this class: https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java (you'll need to set the config yourself) in your project.

**Comment by MircoCagni** [comment]
How set config file? And lhost parameter? 
Thanks :)

**Comment by timwr** [comment]
https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java#L69

**Comment by MircoCagni** [comment]
Yeah, i understand i must change configByte for set lhost (i think) but i dont understand how ti get my ip in format ipv4 (like 127.0.0.1) ti format in Payload class 🙁

**Comment by timwr** [comment]
Use a url, e.g https://github.com/rapid7/metasploit-payloads/blob/master/java/androidpayload/app/src/com/metasploit/stage/Payload.java#L136

**Comment by MircoCagni** [comment]
I hade try to set the server host adding in line 137 of payload class
`url = "tcp://<host>:<port>";`
but when I try to compile it, I have 7 error :(

error: cannot find symbol class Config |  
-- | --
error: cannot find symbol variable ConfigParser |  
error: cannot find symbol variable Config |  
error: cannot find symbol variable Config |  
error: cannot find symbol class TransportConfig |  
error: cannot find symbol variable Config |  
error: cannot find symbol variable PayloadTrustManager |

**Comment by timwr** [comment]
You'll need to delete all references to those classes.
I'm happy to help but GitHub is meant for issues. 
There are also lots of resources for doing what you're trying to achieve on Google. You can even just inject into an existing APK:
https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/payload/android/meterpreter/injection.md
