### ISSUE TITLE
Update pom.xml Files

### ISSUE THREAD

**Issue by CorrM** [rapid7/metasploit-payloads#335]
Can compile without this changes

Plugin: (maven-antrun-plugin)
`<version>1.7</version>` to `<version>1.8</version>`
`<touch datetime="01/01/2000 00:00 AM">` to `<touch>`

Plugin: (maven-compiler-plugin)
`<source>1.5</source>` to `<source>1.6</source>`
`<target>1.5</target>` to `<target>1.6</target>`

**Comment by timwr** [comment]
What error are you seeing? Do you have the right jdk version?

**Comment by CorrM** [comment]
> What error are you seeing? Do you have the right jdk version?
Maven 3.6.0
jdk8.

Errors:
DateTimeParseException => in maven-antrun-plugin
Maven not support 1.5 => maven-compiler-plugin
=====================
new problem :
after i solved all problem and just build and use the android payload i get this shit here :'(
```
[*] Sending stage (43727 bytes) to 192.168.1.6
[*] Meterpreter session 1 opened (192.168.1.5:4444 -> 192.168.1.6:58519) at 2019-03-31 02:53:54 -0400
[*] Sending stage (43727 bytes) to 192.168.1.6
[*] Meterpreter session 2 opened (192.168.1.5:4444 -> 192.168.1.6:45509) at 2019-03-31 02:53:56 -0400
[*] 192.168.1.6 - Meterpreter session 1 closed.  Reason: Died
[*] 192.168.1.6 - Meterpreter session 2 closed.  Reason: Died
[*] Sending stage (43727 bytes) to 192.168.1.6
[*] Meterpreter session 3 opened (192.168.1.5:4444 -> 192.168.1.6:42785) at 2019-03-31 02:54:04 -0400
[*] Sending stage (43727 bytes) to 192.168.1.6
[*] Meterpreter session 4 opened (192.168.1.5:4444 -> 192.168.1.6:37560) at 2019-03-31 02:54:07 -0400
```

why it's 43727 bytes, and session just opens to close it self

**Comment by timwr** [comment]
Can you try mvn 3.5.4?
It works for me:
```
$ mvn -v
Apache Maven 3.5.4
Maven home: /usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-16-generic", arch: "amd64", family: "unix"
```
Which OS are you on? I'm on ubuntu 18.10

**Comment by CorrM** [comment]
Can you try mvn 3.5.4?
yeah i know it's work but to use the last version. it's good to update
