### ISSUE TITLE
Upgrade Kiwi

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-payloads#35]
Not only is Kiwi out of date, but the code has diverged quite a lot from the current implementation. I need to work with @gentilkiwi to come up with a way of making it easier to include without the pain I have with keeping things in sync.

**Comment by jlee-r7** [comment]
@OJ bump.  =)

**Comment by OJ** [comment]
Yeah I've been thinking a lot about this. Before I can merge the latest features into Kiwi, I need to have a chat with @gentilkiwi about giving him a PR that will hopefully make it easier for the code bases to remain relatively close. The code has diverged too much, and some changes are actively conflicting.

In short, I basically need to "do it again". Which isn't a small job :)

**Comment by mubix** [comment]
Can I add a request that one of the features be to export kerberos tickets in base64 (so they don't touch disk on victim) and then maybe even store them in binary format in the loot directory? ;-)

**Comment by OJ** [comment]
They don't touch disk on the victim now?
And they are stored in binary in loot :)

**Comment by OJ** [comment]
OK this is underway.

* PR open on mimikatz here: https://github.com/gentilkiwi/mimikatz/pull/53
* Payloads branch here: https://github.com/OJ/metasploit-payloads/tree/kiwi-update
* Framework branch here: https://github.com/OJ/metasploit-framework/tree/kiwi-update

I see a few hurdles coming, but this approach has minimal impact on Mimikatz and means we'll have Ben's repo as a submodule for future updates, so hopefully adding new features won't be painful.

Watch this space!

**Comment by OJ** [comment]
That legend @gentilkiwi is helping me out as well! We've got a plan to move forward with some of the other hurdles that will make it easier to get the non-text content out as well.

Progress is happening!

**Comment by egypt** [comment]
@OJ Is this issue fixed by #160 ?

**Comment by OJ** [comment]
Yes, this has indeed been fixed by #160, thanks @egypt !
