### ISSUE TITLE
i need to edit the source code and ideas?

### ISSUE THREAD

**Issue by zaramhara** [rapid7/metasploit-payloads#396]
hello 
i am want to modify android payload on windows is that possible??

**Comment by smcintyre-r7** [comment]
Yes it is! So while this is the payloads repository, most of the information is documented in the Metasploit [WIki](https://github.com/rapid7/metasploit-framework/wiki). I'd specifically suggest you look at the pages under the [Getting Started](https://github.com/rapid7/metasploit-framework/wiki#getting-started) section.

The gist is you'll want to setup your development environment, use `git` to clone down the repos, make your edits and then build your thing. If you feel like contributing your changes back to the project so they can be used by others then check out the pages under the [Contributing](https://github.com/rapid7/metasploit-framework/wiki#contributing) section of the wiki.

Thanks for your interest in the Metasploit Framework!
