### ISSUE TITLE
suggestion: meterpreter extension for container with encrypt fs, for store our payloads and files on disk in encrypted state.

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-payloads#409]

**Comment by h00die** [comment]
what would be the benefit to a penetration test, as metasploit is a penetration testing software?  This seems more like a ransomware function.

**Comment by Narutto2011** [comment]
No! We can create a encrypt file system with fat or ntfs, and store next stage there.

**Comment by Narutto2011** [comment]
Like this:
https://github.com/nyx0/Rovnix/tree/master/FsLib
