### ISSUE TITLE
Reflective DLL Injection not working (Rapid7's fork with mingw compilation support)

### ISSUE THREAD

**Issue by quantumcore** [rapid7/metasploit-payloads#430]
I've been playing around with the Reflective DLL injection code, I can compile the Dll's in mingw easily and inject them using the original compiled binaries given [here](https://github.com/stephenfewer/ReflectiveDLLInjection/tree/master/bin) I can also compile the Injector with no Errors, But the injector doesn't work and gives me this on Each time, on every Process, As Administrator, And using precompiled injection dlls.

```
$ gcc GetProcAddressR.c Inject.c LoadLibraryR.c
$ ./a <pid> <dll>
$ [-] Failed to inject the DLL. Error=998
```

Is there anything I'm doing wrong? 
Using this : https://github.com/rapid7/ReflectiveDLLInjection
Due to this I've tried switching my compilers (because I thought it may be it's problem) from Mingw-64 to Mingw to TDM GCC (this one is easy to use, So I'll keep this one). But it doesn't work on either of them. I don't use nor like msvc or visual studio.

The dlls work great, Tested with meterepreter post module reflective dll injection, And also the binary injector given by stephen fewer. 
But injector does not work, And gives error 998 everytime. Every damn time.

**Comment by OJ** [comment]
That's correct. We don't use the injector so it's not really on the radar. But I can easily fix it.

**Comment by quantumcore** [comment]
@OJ Hi! Thanks for reply! I'm just testing out the code and trying to understand how it works. I can't get the injector to work. Can you help me figure out whats the problem? I'm not using the entire meterpreter just testing the Reflective DLL Injection Code.

**Comment by quantumcore** [comment]
Also, I'm on Windows 10 x64.

**Comment by quantumcore** [comment]
Tested rapid7's fork on Visual Studio 2019. Not working.
However, This does work with Visual studio. https://github.com/stephenfewer/ReflectiveDLLInjection
But why doesn't it work with mingw? And How can I make it work?

**Comment by quantumcore** [comment]
It was my own mistake, I have figured out what was the issue. Sorry for this.
