### ISSUE TITLE
Root makefile expects meterpreter c binaries to be in arch-specific folders

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-payloads#433]
Basically, there's a disagreement between the meterpreter makefile and the c/meterpreter makefile.
The meterpreter makefile assumes that the windows binaries will be in two folders according to architecture.  The new c/meterpreter makefile no longer creates those files, and instead, just has the files end in `arch.dll`.  We need to update the parent makefile to copy the arch files rather than the folder contents.

**Comment by timwr** [comment]
Fixed by https://github.com/rapid7/metasploit-payloads/pull/435
