### ISSUE TITLE
what is the reason for class TLVPacket not using generic?

### ISSUE THREAD

**Issue by XenoAmess** [rapid7/metasploit-payloads#470]
https://github.com/rapid7/metasploit-payloads/blob/badaaa4df20be176b5c416d14dcc5148ae1610de/java/meterpreter/meterpreter/src/main/java/com/metasploit/meterpreter/TLVPacket.java#L20

**Comment by timwr** [comment]
I think this is for historical reasons (supporting older java versions), but it's definitely not worth refactoring it now.
