### ISSUE TITLE
Parameter sequence incorrect passing in the createConnection method in the HTTPTransport class

### ISSUE THREAD

**Issue by XhstormR** [rapid7/metasploit-payloads#487]
https://github.com/rapid7/metasploit-payloads/blob/master/java/meterpreter/meterpreter/src/main/java/com/metasploit/meterpreter/HttpTransport.java#L256

Should be:

```java
HttpConnection.addRequestHeaders(conn, customHeaders, userAgent);
```

**Comment by timwr** [comment]
Well spotted, that looks like a bug, I'm not sure why it's not broken at the moment.
Can you send a pull request to fix it? If not we can do it.
Does this fix https://github.com/rapid7/metasploit-framework/issues/15157 or have any noticeable difference?

**Comment by XhstormR** [comment]
This is mainly related to the user-defined header, and will not affect the main functions of the meterpreter.

In my opinion, the problem with https://github.com/rapid7/metasploit-framework/issues/15157 is that when the meterpreter polling commands, the session GUID is not passed in the get request, resulting in the inability of metasploit to distinguish different meterpreter instances。
