### ISSUE TITLE
detected by EDR due to traffic: Botnet

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [rapid7/metasploit-payloads#508]
How is meterpreter detected as Botnet?
Even if https and custom certificates are used. Even if the endpoint is localhost:443.

Http on the other hand is not detected (at least in my specific case) - so is that a telemetry based thing? How would that work and what could be done in order to generically prevent detection via that approach?

**Comment by smcintyre-r7** [comment]
Closing this as a duplicate of https://github.com/rapid7/metasploit-framework/issues/15876.
