### ISSUE TITLE
Update instructions to get POSIX building on Fedora

### ISSUE THREAD

**Issue by OJ** [rapid7/metasploit-payloads#54]
The README currently says:

> Fedora 21: yum install gcc jam make flex patch bison glibc-devel.i686 libgcc.i686

Even with these things installed I'm unable to build `libm` (which is just the second step).

```
$ make
Building libc
Building libm
Makefile:74: recipe for target '/home/oj/code/metasploit-payloads/c/meterpreter/source/bionic/compiled/libm.so' failed
make: *** [/home/oj/code/metasploit-payloads/c/meterpreter/source/bionic/compiled/libm.so] Error 2
$ tail build.log
s_sinf.o: In function `__kernel_sindf.localalias.0':
s_sinf.c:(.text+0x6d): multiple definition of `__kernel_sindf'
k_sinf.o:k_sinf.c:(.text+0x0): first defined here
s_tanf.o: In function `__kernel_tandf.localalias.0':
s_tanf.c:(.text+0x0): multiple definition of `__kernel_tandf'
k_tanf.o:k_tanf.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Makefile.msf:225: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/oj/code/metasploit-payloads/c/meterpreter/source/bionic/libm'
```

I'm investigating now, but would love some insights from the legendary master of POSIX, @bcook-r7.

**Comment by m1m1x** [comment]
Hi threre,
I do encounter the extact same problem when building the posix meterpreter with debian testing (Stretch/x64).
Any update on this matter?

Thanks in advance

**Comment by bcook-r7** [comment]
Hi, a patch like this should do the trick:
```
diff --git a/c/meterpreter/source/bionic/libm/Makefile.msf b/c/meterpreter/source/bionic/l
index f9ae4bd..ff29fd5 100644
--- a/c/meterpreter/source/bionic/libm/Makefile.msf
+++ b/c/meterpreter/source/bionic/libm/Makefile.msf
@@ -10,6 +10,7 @@ CFLAGS+=-I../libc/kernel/common/ -I../libc/arch-${TARGET_ARCH}/include/ 
 CFLAGS+=-D_BYTE_ORDER=_LITTLE_ENDIAN -Ihack/ -I${TARGET_FPU} -I../libc/arch-${TARGET_ARCH
 CFLAGS+=-fPIC -DPIC
 CFLAGS+=-Wl,--hash-style=sysv
+CFLAGS+=-Wl,--allow-multiple-definition
 CFLAGS+=-march=i386 -m32
 
 libm_common_src_files= \
```

HT @acammack-r7

**Comment by bcook-r7** [comment]
Alternately, maybe we should document how to build with the pre-configured meterpreter docker image found here: https://hub.docker.com/r/rapid7/build/tags/

The benefit of using that is that it also includes PHP, Python, Wine, Android SDK/NDK, etc. - pretty much everything you would need to get started quickly without having to sort out dependencies (other than getting docker itself running :) - I think @trosen-r7 had done a write-up on how to build all of the meterpreters with docker, but looks like it didn't make it into a PR :(

**Comment by m1m1x** [comment]
Your patch is working on debian. Thanks!
