### ISSUE TITLE
Payload creation process not proceeding

### ISSUE THREAD

**Issue by Samshow-cyber** [rapid7/metasploit-payloads#544]
I solved the apktool issue after making some researches. But I have another issue ongoing.

I'm trying to add payload to an apk file. I followed the normal command format and processed the command in the CMD. This is what I got:

```
Using apk template: theapk.apk
[-] No platform was selected, choosing Msf::module::platform::Android from #the payload
[-] No arch selected, selecting arch: dalvik from payload
```

And after that, nothing more... the command prompt it still processing (still blinking the white dash)

Please why is this happening? Please help!

**Comment by Samshow-cyber** [comment]
Anyone?

**Comment by bcoles** [comment]
Dupe of #543
