### ISSUE TITLE
Payload apk not working after installation

### ISSUE THREAD

**Issue by Samshow-cyber** [rapid7/metasploit-payloads#546]
Hello! I need help. I injected a payload to a trusted apk and it was successful. I installed the apk on my android device and it was successfully installed but when I opened the app, it says webpage not available.

Why is this happening? Please anyone. Thanks

**Comment by bcoles** [comment]
> Why is this happening?

Presumably the website is not available.

**Comment by Samshow-cyber** [comment]
Ops ok. But is that why my meterpreter session dying?

**Comment by bcoles** [comment]
There is not enough information to reproduce this issue.

**Comment by gwillcox-r7** [comment]
Closing issue. Insufficient information and no additional info provided after request for info.
