### ISSUE TITLE
RFC: BOF-Runner Extension

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-payloads#576]
Given the reasonably constrained DSL and functionality of (most) beacon object files, it strikes me that turnabout would be fair play and that meterp should well be able to link and run most of the PIC object files generated for "that platform." Their head-end syntax should be pretty easy to parse w/ Ruby so as to pack args, read bins, and execute in the extension's process space after sending the resulting TLV over the wire.
Ping @Oj @zeroSteiner for gut check and higher-level thoughts if that passes :).

**Comment by sempervictus** [comment]
Looks like similar efforts have been undertaken using PSH - https://github.com/airbus-cert/Invoke-Bof/blob/main/Invoke-Bof.ps1

**Comment by zeroSteiner** [comment]
Yeah, this might make for a useful extension. I am apprehensive about parsing the scripting language but I guess Sliver uses a JSON based alternative format that perhaps we could conform to. I'll have to give this some more thought. It seems feasible for the Windows and Python implementations.
