### ISSUE TITLE
Maven compile androidpayload parse keystore error

### ISSUE THREAD

**Issue by Muhammedsrhn** [rapid7/metasploit-payloads#603]

**Comment by timwr** [comment]
Are you sure you're using java 8? You can check with `java -version`

**Comment by Muhammedsrhn** [comment]
ı have this version
┌──(root㉿kali)-[~]
└─# java -version 
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by Muhammedsrhn** [comment]
ı solved problem but now ı deploy compiler result to /opt/mymetasploit/metasploit-framework/ 
Files are coming, but msfvenom brings me defaul files, for example, I change MainActivity, msfvenom becomes apk but it does not add my changes

**Comment by Muhammedsrhn** [comment]
> Java 8 kullandığınızdan emin misiniz? ile kontrol edebilirsiniz`java -version`

ı solved problem but now ı deploy compiler result to /opt/mymetasploit/metasploit-framework/
Files are coming, but msfvenom brings me defaul files, for example, I change MainActivity, msfvenom becomes apk but it does not add my changes

**Comment by gwillcox-r7** [comment]
Closing due to insufficient information.
