### ISSUE TITLE
In Android msfvenom payload

### ISSUE THREAD

**Issue by Mathiacademy** [rapid7/metasploit-payloads#635]
In Android msfvenom payload meterpreter only shows sysinfo and other services are not available for example, webcam_stream, sdcard etc etc. the phone version is android v10, v11.

**Comment by smcintyre-r7** [comment]
Have you loaded the android extension? Those commands are provided by an extension.

**Comment by nb3rn** [comment]
same problem,
but my problem I cannot open <code>webcam_stream</code> result.
I try with <code>termux-open --chooser</code> and open with chrome,but still not showing the result stream from my victim.please help me friend.

**Comment by h00die** [comment]
Likely https://github.com/rapid7/metasploit-framework/issues/19154 related, its a permissions issue with the old android payloads
