### ISSUE TITLE
Meterpreter does not detect a reverse connection from the payload even after executing the payload on the target android 

### ISSUE THREAD

**Issue by R5x1x1** [rapid7/metasploit-payloads#691]
When i use the meterpreter and when i just reach to the active the payload apk file and starting it on my phone and give it Permissions the meterpreter doesn't reverse any information and the multi/handler still waiting the device for connecting Knowing that I but the port 4444 and 8888 and 8080 and use my Linux on virtual box

**Comment by tactipus** [comment]
Hi! Would you provide more info on how to reproduce the problem on my mind? TYIA!

**Comment by Morsmalleo** [comment]
> When i use the meterpreter and when i just reach to the active the payload apk file and starting it on my phone and give it Permissions the meterpreter doesn't reverse any information and the multi/handler still waiting the device for connecting Knowing that I but the port 4444 and 8888 and 8080 and use my Linux on virtual box

Make sure your network settings for your Linux Virtual Machine in VirtualBox is set to Bridged Adapter otherwise meterpreter connection won't work from VM's.
