### ISSUE TITLE
Metasploit Android 14 Msf venom payload Not working 

### ISSUE THREAD

**Issue by Thegsmwork** [rapid7/metasploit-payloads#706]
I have created a payload using  @Metasploit with the help of MSF Venom. When you open this payload, it requests permissions to access various things. If you grant permission, the payload runs. This is how a normal Metasploit payload works. Now, my issue is that I created the payload and I'm trying to install it on Android 14, but I'm encountering this error. I'll send an image. When I increase the SDK version, the error gets fixed, but then the payload doesn't ask for permissions like a normal APK does. It just installs. During editing, I didn't change any code other than increasing the target SDK version. Can you please help me with this?

Any idea ?
![Screenshot_2024-06-15-15-33-22-01_3d73e98b1ad3bd2575f7a56513d89a0c](https://github.com/rapid7/metasploit-payloads/assets/98774023/1bf1447e-9a6e-4ef0-a3f3-e81f4aaff8ba)

**Comment by glare786** [comment]
After making pylod go to apkmod M and sing apk apk2 and changing sdk v 34/38 and save apk

**Comment by Hackxtra07** [comment]
I can help out a little  I successful able to install it on the Android 16 phone the sdk version in the apktool.Yml  to be 24 and 36 and also some changes In thr Android manifest file some more fixed if wanna know can contact me on my mail
