### ISSUE TITLE
Meterpreter (Win/Native) breaks when host has > 20 IPs

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-payloads#82]
Heap bug here:
```
DWORD get_interfaces_windows(Remote *remote, Packet *response) in metasploit-payloads/c/meterpreter/source/extensions/stdapi/server/net/config/interface.c
```

**Comment by mubix** [comment]
@OJ ^

**Comment by mubix** [comment]
Specifically https://github.com/rapid7/metasploit-payloads/blob/master/c/meterpreter/source/extensions/stdapi/server/net/config/interface.c#L106

**Comment by OJ** [comment]
I'll take this one. Thanks @mubix.

**Comment by OJ** [comment]
This will be an easy fix, I'll just move the code over to use group packets and then the up-front malloc won't be necessary.

**Comment by busterb** [comment]
posix looks like it will explode on 10 ips; if you get your rework in, will update that side. Also, I think the outer do { } while(0);s could probably be excised, since there would be only one real error condition (and you could just return getlasterror on that)

**Comment by mubix** [comment]
Easy enough to add IP addresses for testing - run the following in a admin prompt
```
FOR /L %A IN (0,1,20) DO netsh interface ipv4 add address "Local Area Connection" 10.%A.%A.%A 255.255.255.0
```

**Comment by mubix** [comment]
Looks fixed. Thanks!
